{% set name = "dacite" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6257a5e505b61a8cafee7ef3ad08cf32ee9b885718f42395d017e0a9b4c6af65

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - dataclasses
  run:
    - python >=3.6
    - dataclasses

test:
  imports:
    - dacite
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/konradhalas/dacite
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple creation of data classes from dictionaries.

extra:
  recipe-maintainers:
    - mands
    - rxm7706
