{% set name = "dacite" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 683a1d72c8fa0c0341034ddabc7a5c6f6ddc188033a26784417a9429dd3ffa51

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - dataclasses
  run:
    - python >=3.6
    - dataclasses

test:
  imports:
    - dacite
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/konradhalas/dacite
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple creation of data classes from dictionaries.

extra:
  recipe-maintainers:
    - mands
    - rxm7706
