{% set name = "dacite" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/konradhalas/dacite/archive/v{{ version }}.tar.gz
  sha256: 5e06b2c9447cb978316590c1d51d75b4fd89e210208802d7d00f21408a186089

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - dacite
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/konradhalas/dacite
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple creation of data classes from dictionaries.

extra:
  recipe-maintainers:
    - mands
    - rxm7706
